# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WorldIcon' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

   pod 'Masonry', '~> 1.0.2'
   pod 'SDWebImage', '~> 3.7’
   pod 'MJRefresh', '~> 3.1.12'
   pod 'JSONModel', '~> 1.7.0'
  # Pods for WorldIcon

end
